#[path = "assets/assets_module.rs"]
pub mod assets;
#[path = "audio/audio_module.rs"]
pub mod audio;
#[path = "ecs/ecs_module.rs"]
pub mod ecs;
#[path = "ecs/job_system.rs"]
pub mod job_system;
#[path = "graphics/graphics_module.rs"]
pub mod graphics;
#[path = "input/input_module.rs"]
pub mod input;
pub mod physics;
#[path = "render/render_module.rs"]
pub mod render;
#[path = "ui/ui_module.rs"]
pub mod ui;
pub mod profiler;
pub mod engine;
#[path = "world/world_module.rs"]
pub mod world;
#[path = "weather/weather_module.rs"]
pub mod weather;
#[path = "game/mission_save.rs"]
pub mod game;

pub use assets::*;
pub use ecs::*;
pub use physics::*;
pub use graphics::*;
pub use audio::*;
pub use ui::*;
pub use profiler::*;
pub use engine::*;
pub use world::*;
pub use weather::*;
pub use game::*;

// Core engine types re-export
pub use nalgebra;
pub use rapier3d;
pub use wgpu;
pub use winit;
pub use glam;